language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.7 DRF=3.1
  - DJANGO=1.7 DRF=3.2
  - DJANGO=1.8 DRF=3.1
  - DJANGO=1.8 DRF=3.2
  - DJANGO=1.9 DRF=3.2
  - DJANGO=1.9 DRF=3.3
matrix:
  exclude:
   - python: "3.5"
     env: DJANGO=1.7 DRF=3.1
   - python: "3.5"
     env: DJANGO=1.7 DRF=3.2
install:
  - pip install -q Django==$DJANGO
  - pip install -q djangorestframework==$DRF
  - pip install pep8
  - pip install -q -e .
before_script:
  - "pep8 drf_generators --exclude=templates && cd tests"
script:
  - python manage.py test
